Refactoring of NodeJs server application

diff --git a/docker-jenkins/Jenkinsfile.server b/docker-jenkins/Jenkinsfile.server
--- a/docker-jenkins/Jenkinsfile.server
+++ b/docker-jenkins/Jenkinsfile.server
@@ -7,9 +7,9 @@ pipeline {
 
     stages {
         stage('Conditional Execution') {
-            // when {
-            //     changeset "**/server/**"
-            // }
+            when {
+                changeset "**/server/**"
+            }
             stages {
                 stage('Old Builds Cleanup') {
                     steps {
@@ -61,85 +61,85 @@ pipeline {
                     }
                 }
 
-                // stage('Install Dependencies') { 
-                //     steps {
-                //         script {
-                //             sh '''
-                //                 cd server
-                //                 npm install --omit=optional --no-audit --force --no-bin-links --loglevel verbose | tee -a /home/ubuntu/docker-jenkins/npm_install.log
-                //             '''
-                //         }
-                //     }
-                // }
+                stage('Install Dependencies') { 
+                    steps {
+                        script {
+                            sh '''
+                                cd server
+                                npm install --omit=optional --no-audit --force --no-bin-links --loglevel verbose | tee -a /home/ubuntu/docker-jenkins/npm_install.log
+                            '''
+                        }
+                    }
+                }
 
-                // stage('Unit Test') { 
-                //     steps {
-                //         script {
-                //             // Start the Express Test server in the background
-                //             def server = sh(script: '''
-                //                 # Load NVM
-                //                 export NVM_DIR="$HOME/.nvm"
-                //                 [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
+                stage('Unit Test') { 
+                    steps {
+                        script {
+                            // Start the Express Test server in the background
+                            def server = sh(script: '''
+                                # Load NVM
+                                export NVM_DIR="$HOME/.nvm"
+                                [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
 
-                //                 # Start the server in the background
-                //                 nohup node server/test.server.js > server.log 2>&1 & echo $!
-                //             ''', returnStdout: true).trim()
+                                # Start the server in the background
+                                nohup node server/test.server.js > server.log 2>&1 & echo $!
+                            ''', returnStdout: true).trim()
 
-                //             echo "Server PID: ${server}"
+                            echo "Server PID: ${server}"
 
-                //             def r = sh(script: 'curl -I http://0.0.0.0:5000/test-server || echo "Error"', returnStdout: true).trim()
-                //             echo "Curl response: ${r}"
+                            def r = sh(script: 'curl -I http://0.0.0.0:5000/test-server || echo "Error"', returnStdout: true).trim()
+                            echo "Curl response: ${r}"
 
-                //             // Check the last few lines of the server log
-                //             sh 'tail -n 15 server.log'
+                            // Check the last few lines of the server log
+                            sh 'tail -n 15 server.log'
 
-                //             // Wait for the server to be ready
-                //             def maxRetries = 10
-                //             def retries = 0
-                //             def isServerReady = false
+                            // Wait for the server to be ready
+                            def maxRetries = 10
+                            def retries = 0
+                            def isServerReady = false
                             
-                //             // Check and kill any running Node.js processes
-                //             def killNodeProcesses = sh(script: '''
-                //                 echo "Checking for running Node.js processes..."
-                //                 PIDS=$(ps aux | grep '[n]ode' | awk '{print $2}')
-                //                 if [ -n "$PIDS" ]; then
-                //                     echo "Killing existing Node.js processes: $PIDS"
-                //                     for pid in $PIDS; do
-                //                         kill -9 $pid || echo "Failed to kill process $pid"
-                //                     done
-                //                 else
-                //                     echo "No Node.js processes found."
-                //                 fi
-                //             ''', returnStdout: true).trim()
+                            // Check and kill any running Node.js processes
+                            def killNodeProcesses = sh(script: '''
+                                echo "Checking for running Node.js processes..."
+                                PIDS=$(ps aux | grep '[n]ode' | awk '{print $2}')
+                                if [ -n "$PIDS" ]; then
+                                    echo "Killing existing Node.js processes: $PIDS"
+                                    for pid in $PIDS; do
+                                        kill -9 $pid || echo "Failed to kill process $pid"
+                                    done
+                                else
+                                    echo "No Node.js processes found."
+                                fi
+                            ''', returnStdout: true).trim()
 
-                //             while (retries < maxRetries && !isServerReady) {
-                //                 sleep(20)
-                //                 def result = sh(script: 'curl -o /dev/null -w "%{http_code}" http://0.0.0.0:5000/test-server', returnStdout: true).trim()
-                //                 echo "result: ${result}"
+                            while (retries < maxRetries && !isServerReady) {
+                                sleep(20)
+                                def result = sh(script: 'curl -o /dev/null -w "%{http_code}" http://0.0.0.0:5000/test-server', returnStdout: true).trim()
+                                echo "result: ${result}"
 
-                //                 if (result == '200') {
-                //                     isServerReady = true
-                //                     echo 'Server is ready.'
-                //                 } else {
-                //                     retries++
-                //                     echo "Attempt ${retries}: Server not ready yet."
-                //                 }
-                //             }
+                                if (result == '200') {
+                                    isServerReady = true
+                                    echo 'Server is ready.'
+                                } else {
+                                    retries++
+                                    echo "Attempt ${retries}: Server not ready yet."
+                                }
+                            }
 
-                //             if (!isServerReady) {
-                //                 error "Server did not start in time."
-                //             }
-                //         }
-                //     }
-                // }
+                            if (!isServerReady) {
+                                error "Server did not start in time."
+                            }
+                        }
+                    }
+                }
 
-                // stage('Approve PROD Deployment') {
-                //     steps {
-                //         timeout(time: 1, unit: 'HOURS') {
-                //             input message: 'Deploy changes to PROD?', ok: 'Deploy' 
-                //         }
-                //     }
-                // }
+                stage('Approve PROD Deployment') {
+                    steps {
+                        timeout(time: 1, unit: 'HOURS') {
+                            input message: 'Deploy changes to PROD?', ok: 'Deploy' 
+                        }
+                    }
+                }
 
                 stage('Deploy to PROD') {
                     steps {
