Issue #20-Commit for testing Jenkins server pipeline

diff --git a/jenkins/Jenkinsfile.server b/jenkins/Jenkinsfile.server
--- a/jenkins/Jenkinsfile.server
+++ b/jenkins/Jenkinsfile.server
@@ -92,6 +92,9 @@ pipeline {
 
                             echo "Server PID: ${server}"
 
+                            def r = sh(script: 'curl -I http://localhost:5000/test-server || echo "Error"', returnStdout: true).trim()
+                            echo "Curl response: ${r}"
+
                             // Check the last few lines of the server log
                             sh 'tail -n 15 server.log'
 
