Commit for testing Jenkins

diff --git a/jenkins/Jenkinsfile.server b/jenkins/Jenkinsfile.server
--- a/jenkins/Jenkinsfile.server
+++ b/jenkins/Jenkinsfile.server
@@ -21,6 +21,14 @@ pipeline {
                                 export NVM_DIR=\"/home/ubuntu/.nvm\"
                                 [ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"
                                 export PATH=\"$NVM_DIR/versions/node/\$(nvm version)/bin:\$PATH\"
+
+                                echo "Current shell: $SHELL"
+                                echo "Current PATH: $PATH"
+
+                                command -v nvm || { echo "nvm not found"; exit 1; }
+                                command -v pm2 || { echo "pm2 not found"; exit 1; }
+                                
+                                nvm use default || nvm install node
                                 pm2 restart server" > /tmp/deploy.sh
                                 chmod +x /tmp/deploy.sh
                             '
