Commit for testing Jenkins

diff --git a/jenkins/Jenkinsfile.server b/jenkins/Jenkinsfile.server
--- a/jenkins/Jenkinsfile.server
+++ b/jenkins/Jenkinsfile.server
@@ -17,10 +17,6 @@ pipeline {
                             command -v nvm || echo "nvm not found"
                             echo "NVM loaded: $(command -v nvm)"
 
-                            # Ensure the desired Node.js version is installed
-                            nvm install 21.7.2
-                            nvm alias default 21.7.2
-
                             # Copy JavaScript files
                             scp -i /root/.ssh/vegan-mundi.pem -o StrictHostKeyChecking=no server/*.js ubuntu@172.31.29.148:/var/www/vegan-mundi/server/
 
@@ -29,14 +25,16 @@ pipeline {
 
                             # Restart the server using pm2
                             ssh -i /root/.ssh/vegan-mundi.pem -o StrictHostKeyChecking=no ubuntu@172.31.29.148 '
-                                export NVM_DIR="/root/.nvm"
-                                [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
+                                bash -l -c "
+                                export NVM_DIR=\\"/root/.nvm\\"
+                                [ -s \\"$NVM_DIR/nvm.sh\\" ] && . \\"$NVM_DIR/nvm.sh\\"
                                 
                                 # Check if nvm is available
-                                command -v nvm || echo "nvm not found"
-                                echo "NVM loaded: $(command -v nvm)"
+                                command -v nvm || echo \\"nvm not found\\"
+                                echo \\"NVM loaded: \$(command -v nvm)\\"
                                 
                                 nvm use default && pm2 restart server
+                                "
                             '
                         '''
                     }
